@@include('app.js', {})
@@include('sliders.js', {})
@@include('show-password.js', {})
@@include('agreeDeleteModal.js',{})
@@include('stepForm.js',{})
@@include('radio-tabs.js',{})
@@include('phone-mask.js',{})